# Dockerfile.base
FROM ruby:3.1-slim-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN gem update --system && gem install jekyll && gem cleanup

EXPOSE 4000

WORKDIR /site

COPY docker-entrypoint.sh /usr/local/bin/
